<?php

namespace AppBundle\Repository;

/**
 * AccesReferenceServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccesReferenceServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByServiceReference($service, $reference)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:AccesReferenceService a
                 WHERE  a.service = :service
                 AND    a.reference = :reference'
            )->setParameter('service', $service)
            ->setParameter('reference', $reference)
            ->getResult();
    }
    
    public function findByServiceAgence($service, $agence)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:AccesReferenceService a
                    JOIN   a.guichet g
                    WHERE  a.service = :service
                    AND g.agence = :agence'
            )->setParameter('service', $service)
             ->setParameter('agence', $agence)
                ->getResult();
    }
    
    public function findByService($service)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:AccesReferenceService a
                    WHERE  a.service = :service
                    '
            )->setParameter('service', $service)
                ->getResult();
    }
    
    public function findByServiceAgences($service)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT e.id, e.nom FROM AppBundle:AccesReferenceService a
                    JOIN a.guichet  g
                    JOIN g.agence  e
                    WHERE  a.service = :service
                    ORDER BY e.nom'
            )->setParameter('service', $service)
            ->getResult();
    }
    
    public function findByUserService($user, $service)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT e.id, e.nom FROM AppBundle:AccesReferenceService a
                    JOIN   a.service s
                    JOIN   s.service t
                    JOIN   s.entreprise e
                    WHERE  a.usager = :user
                    AND t.service = :service'
            )->setParameter('user', $user)
             ->setParameter('service', $service)
                ->getResult();
    }
    
    public function findByUserServiceEntreprise($user, $service, $entreprise)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT e.id, e.nom FROM AppBundle:AccesReferenceService a
                    JOIN   a.service s
                    JOIN   s.service t
                    JOIN   s.entreprise e
                    WHERE  a.usager = :user
                    AND t.service = :service
                    AND s.entreprise = :entreprise'
            )->setParameter('user', $user)
             ->setParameter('service', $service)
             ->setParameter('entreprise', $entreprise)
                ->getResult();
    }
}
