<?php

namespace AppBundle\Repository;

/**
 * AdminEntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminEntrepriseRepository extends \Doctrine\ORM\EntityRepository
{
      public function findOneById($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:AdminEntreprise a
                 WHERE  a.id = :id'
            )->setParameter('id', $id)
            ->getResult();
    }
    
      public function findOneByUser($user)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:AdminEntreprise a
                 WHERE  a.user = :user'
            )->setParameter('user', $user)
            ->getResult();
    }
    
    public function findByEntreprise()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:AdminEntreprise a
                 JOIN   a.entreprise e
                 ORDER BY e.nom'
            )
            ->getResult();
    }
}
