<?php

namespace AppBundle\Repository;

/**
 * AgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAgencesByEntreprise($entreprise)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle:Agence a
                 WHERE  a.entreprise = :entreprise
                 ORDER BY a.nom'
            )->setParameter('entreprise', $entreprise)
             ->getResult();
    }
}
