<?php

namespace AppBundle\Repository;

/**
 * CertificatServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificatServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCertificatService($certificat, $service)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:CertificatService c
                 WHERE    c.certificat = :certificat
                 AND      c.entrepriseservice = :entrepriseservice'
            )->setParameter('certificat', $certificat)
            ->setParameter('entrepriseservice', $service)
             ->getResult();
    }
    
     public function findByCertificatServiceCategorie($certificat, $categorie)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:CertificatService c
                 WHERE    c.certificat = :certificat
                 AND      c.categorie = :categorie'
            )->setParameter('certificat', $certificat)
                ->setParameter('categorie', $categorie)
             ->getResult();
    }
    
    public function findByCertificat($certificat)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:CertificatService c
                 JOIN c.entrepriseservice s
                 WHERE    c.certificat = :certificat
                 ORDER BY s.service'
            )->setParameter('certificat', $certificat)
             ->getResult();
    }
    
    public function findByCertificatFacture($certificat)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:CertificatService c
                 WHERE    c.certificat = :certificat'
            )->setParameter('certificat', $certificat)
             ->getResult();
    }
    
    public function findByLigneServiceCertificat($certificat)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:CertificatService c
                 WHERE    c.certificat = :certificat'
            )->setParameter('certificat', $certificat)
             ->getResult();
    }
}
