<?php

namespace AppBundle\Repository;

/**
 * InfoEntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoEntrepriseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInformationsByEntreprise($entreprise)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i FROM AppBundle:InfoEntreprise i
                 WHERE  i.entreprise = :entreprise'
            )->setParameter('entreprise', $entreprise)
             ->getResult();
    }
    
      public function findByEntreprisePeriode($entreprise, $periode)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT  SUM(i.volume) as somme FROM AppBundle:InfoEntreprise i
                 WHERE    i.entreprise = :entreprise
                 AND      i.date LIKE :periode
                 GROUP BY  i.entreprise'
            )->setParameter('entreprise', $entreprise)
            ->setParameter('periode', $periode)
             ->getResult();
    }
    
      public function findByEntreprisePeriodeEssai($entreprise, $periode)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT  SUM(i.volume) as somme FROM AppBundle:InfoEntreprise i
                 WHERE    i.entreprise = :entreprise
                 AND      i.date LIKE :periode
                 AND      i.essai = :essai
                 GROUP BY  i.entreprise'
            )->setParameter('entreprise', $entreprise)
            ->setParameter('periode', $periode)
                 ->setParameter('essai', 'non')
             ->getResult();
    }
    
    public function findByMsAnneeEntreprise($annee, $entreprise)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT SUBSTRING(i.date, 1, 7) AS periode
                 FROM AppBundle:InfoEntreprise i
                 WHERE i.date LIKE :periode
                 AND   i.entreprise = :entreprise
                 GROUP BY periode
                 ORDER BY periode DESC'
            )->setParameter('periode', $annee)
             ->setParameter('entreprise', $entreprise)
             ->getResult();
    }
    
    public function findByMsAnneeEntrepriseEssai($annee, $entreprise)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT SUBSTRING(i.date, 1, 7) AS periode
                 FROM AppBundle:InfoEntreprise i
                 WHERE i.date LIKE :periode
                 AND   i.entreprise = :entreprise
                 AND   i.essai = :essai
                 GROUP BY periode
                 ORDER BY periode DESC'
            )->setParameter('periode', $annee)
             ->setParameter('entreprise', $entreprise)
             ->setParameter('essai', 'non')
             ->getResult();
    }
    
    public function findByMsAnnee($annee)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT SUBSTRING(c.date, 1, 7) AS periode
                 FROM AppBundle:InfoEntreprise i
                 WHERE i.date LIKE :periode
                 GROUP BY periode
                 ORDER BY periode DESC'
            )->setParameter('periode', $annee)
             ->getResult();
    }
    
    public function findByMsAnneeEssai($annee)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT SUBSTRING(i.date, 1, 7) AS periode
                 FROM AppBundle:InfoEntreprise i
                 WHERE i.date LIKE :periode
                 AND i.essai LIKE :essai
                 GROUP BY periode
                 ORDER BY periode DESC'
            )->setParameter('periode', $annee)
             ->setParameter('essai', 'non')
             ->getResult();
    }
    
     public function findByPeriodeEntreprises($periode)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT  DISTINCT e.id FROM AppBundle:InfoEntreprise i
                 JOIN   i.entreprise e
                 WHERE i.date LIKE :periode'
            )->setParameter('periode', $periode)
             ->getResult();
    }
    
     public function findByPeriodeEntreprisesEssai($periode)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT  DISTINCT e.id FROM AppBundle:InfoEntreprise i
                 JOIN   i.entreprise e
                 WHERE i.date LIKE :periode
                 AND i.essai = :essai'
            )->setParameter('periode', $periode)
                   ->setParameter('essai', 'non')
             ->getResult();
    }
}
