<?php

namespace AppBundle\Repository;

/**
 * TarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifRepository extends \Doctrine\ORM\EntityRepository
{
     public function findOneById($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM AppBundle:Tarif t
                 WHERE  t.id = :id'
            )->setParameter('id', $id)
            ->getResult();
    }
    
    public function findByService($service)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM AppBundle:Tarif t
                 WHERE t.service = :service'
            )->setParameter('service', $service)
             ->getResult();
    }
    
    public function findByOrdre()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM AppBundle:Tarif t
                 ORDER BY t.service'
            )->getResult();
    }
    
    public function findByCategorieBanque()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM AppBundle:Tarif t
                 WHERE  t.service != :service
                 ORDER BY t.service'
            )->setParameter('service', 'Factures')
             ->getResult();
    }
    
    
    
    public function findByCategorieEntreprise()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM AppBundle:Tarif t
                 WHERE  t.service != :service1
                 AND    t.service != :service2
                 ORDER BY t.service'
            )->setParameter('service1', 'Avis de Banque')
             ->setParameter('service2', 'Relevés de Compte')
             ->getResult();
    }
}
