<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
      public function findOneById($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:User u
                 WHERE  u.id = :id'
            )->setParameter('id', $id)
            ->getResult();
    }
    
    public function findOneByEmailId($email, $id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:User u
                 WHERE  u.email = :email
                 AND u.id != :id'
            )->setParameter('email', $email)
            ->setParameter('id', $id)
            ->getResult();
    }
      public function findOneByEmail($email)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:User u
                 WHERE  u.email = :email'
            )->setParameter('email', $email)
            ->getResult();
    }
    
    public function findByCoffres()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:User u
                 WHERE  u.roles = :roles'
            )->setParameter('roles', 'a:1:{i:0;s:11:"ROLE_COFFRE";}')
            ->getResult();
    }
    
    
}
